export const marketInsights = [
  {
    slug: "north-bengaluru-property-guide",
    index: "01",
    title: "North Bengaluru: What Buyers Should Compare",
    category: "Location intelligence",
    summary: "Compare airport-corridor and North Bengaluru opportunities beyond the project brochure.",
    deck: "North Bengaluru brings together established neighbourhoods, airport-led growth corridors, major employment zones, and new residential supply. The useful comparison begins at the micro-market level.",
    readTime: "6 min read",
    hero: { src: "/media/hero-poster.jpg", alt: "Contemporary residential architecture in a landscaped setting", width: 1800, height: 2400 },
    thesis: "Compare everyday connectivity, surrounding development, project stage, total commitment, and how the micro-market fits your life or investment horizon—not simply its distance from the airport.",
    sections: [
      { heading: "Begin with the micro-market", paragraphs: ["Devanahalli, Hebbal, Thanisandra, Yelahanka, Hennur, and the airport corridor serve different daily routines, budgets, and time horizons.", "Look at the roads you will actually use, nearby employment and social infrastructure, neighbourhood maturity, and the development still expected around the project."], fieldNote: "Ask what works today, what is under construction, and what is only proposed." },
      { heading: "Compare the complete property", paragraphs: ["Configuration, usable layout, open space, clubhouse scale, maintenance expectations, handover stage, and developer track record all shape the lived and financial experience.", "A strong location story cannot compensate for a property that does not fit the intended use or total commitment."] },
      { heading: "Verify current project information", paragraphs: ["Inventory, pricing, possession timelines, approvals, charges, and connectivity claims change. Use current project material and route specialist questions to appropriately qualified professionals.", "Hundred Yards can help organise the shortlist and site visits; final verification remains property-specific."] },
    ],
    carryForward: ["Compare micro-markets, not only broad zones.", "Separate current infrastructure from future proposals.", "Verify inventory, price, approvals, charges, and timelines for the specific project."],
    relatedProductSlug: "before-you-buy-field-guide",
  },
  {
    slug: "compare-projects-beyond-price",
    index: "02",
    title: "How to Compare Projects Beyond the Starting Price",
    category: "Buyer guide",
    summary: "A useful comparison includes location, layout, stage, charges, developer delivery, and everyday fit.",
    deck: "The lowest headline price is rarely the complete comparison. Buyers need to understand what the number represents and what the property must deliver over time.",
    readTime: "6 min read",
    hero: { src: "/media/facade-detail.jpg", alt: "Detailed geometric residential facade", width: 1800, height: 1170 },
    thesis: "Compare the total proposition: daily fit, usable layout, project maturity, developer context, complete cost, and the evidence supporting each claim.",
    sections: [
      { heading: "Clarify what the price includes", paragraphs: ["Ask for a current, dated cost sheet and understand the area basis, premiums, parking, deposits, taxes, registration, and other applicable charges.", "Similar starting prices can become different commitments once configuration, area, floor, stage, and exclusions are considered."], fieldNote: "Keep the dated cost sheet beside every project comparison." },
      { heading: "Compare the home you will use", paragraphs: ["Study room dimensions, circulation, light, ventilation, storage, privacy, balcony usability, tower placement, and the relationship between the apartment and shared spaces.", "A brochure area is less useful than understanding whether the plan supports the household, work pattern, or rental audience." ] },
      { heading: "Put delivery and location in context", paragraphs: ["Project stage, developer track record, surrounding infrastructure, access roads, and neighbourhood maturity affect experience and risk.", "Treat future-development claims as items to verify, not as completed benefits already included in the property."] },
    ],
    carryForward: ["Use a complete, dated cost sheet.", "Compare usable layout and daily fit.", "Separate current benefits from future-development claims."],
    relatedProductSlug: "basics-of-real-estate-training-deck",
  },
  {
    slug: "site-visit-checklist",
    index: "03",
    title: "What to Notice During a Property Site Visit",
    category: "Buyer guide",
    summary: "Turn a site visit into a useful record of layout, surroundings, access, condition, and follow-up questions.",
    deck: "A site visit reveals what the brochure cannot: movement, proportion, noise, access, surroundings, and the questions that emerge in person.",
    readTime: "5 min read",
    hero: { src: "/media/interior-daylight.jpg", alt: "Sunlit contemporary residential interior", width: 1800, height: 2700 },
    thesis: "Leave every visit with observations, photographs where permitted, a current cost sheet, and a short list of items that still need verification.",
    sections: [
      { heading: "Experience the approach", paragraphs: ["Notice the final stretch of road, entry and exit movement, surrounding uses, construction activity, public transport, and how the route feels when you are most likely to travel.", "If possible, revisit at another time of day. One quiet afternoon cannot represent every weekday morning or evening."], fieldNote: "Record travel time from a place you actually use—not only from a brochure landmark." },
      { heading: "Read the home as a sequence", paragraphs: ["Walk from entrance to living spaces, bedrooms, kitchen, utilities, balconies, and storage. Notice privacy, door conflicts, furniture zones, daylight, ventilation, and views.", "In a sample apartment, confirm what is standard specification and what has been added only for display." ] },
      { heading: "Finish with the next questions", paragraphs: ["Collect the latest plan, specification, cost sheet, construction or handover context, and the contact responsible for follow-up.", "Property-specific legal, financial, engineering, tax, and documentation questions should be checked with the relevant qualified professionals." ] },
    ],
    carryForward: ["Review access and surroundings as carefully as the apartment.", "Confirm which sample-home elements are standard.", "Leave with current documents and named follow-up questions."],
    relatedProductSlug: "before-you-buy-field-guide",
  },
  {
    slug: "nri-property-search-bengaluru",
    index: "04",
    title: "A Smarter Remote Property Search for NRIs",
    category: "NRI guide",
    summary: "Use focused shortlists, comparable video walkthroughs, local coordination, and independent verification.",
    deck: "Distance does not have to mean an endless stream of project links. A remote search works better when the shortlist, walkthrough, documents, and decision owners stay organised.",
    readTime: "6 min read",
    hero: { src: "/media/interior-soft.jpg", alt: "Quiet contemporary living room", width: 1200, height: 800 },
    thesis: "A reliable remote search combines a precise requirement, comparable video walkthroughs, local market context, and qualified professional review where needed.",
    sections: [
      { heading: "Reduce the shortlist before the call", paragraphs: ["Agree on location, use case, budget range, configuration, timing, and non-negotiables before reviewing projects. A small relevant shortlist is easier to investigate than a large feed of launch material.", "Ask why each project was included and what trade-off separates it from the others." ] },
      { heading: "Make walkthroughs comparable", paragraphs: ["Use the same sequence for each video: approach road, project entry, surroundings, tower context, sample or actual apartment, view, common areas, and unresolved questions.", "Live walkthroughs let the buyer direct attention to details that edited promotional videos may skip."], fieldNote: "Label videos by date, configuration, tower, and whether the unit is a sample or actual inventory." },
      { heading: "Keep coordination and verification clear", paragraphs: ["A Bengaluru-based team can coordinate visits, current project information, follow-ups, and transaction steps. Specialist questions still need the appropriate qualified reviewer.", "Do not send original confidential documents or payment details through an initial website enquiry." ] },
    ],
    carryForward: ["Start with a small, reasoned shortlist.", "Use the same walkthrough structure for every option.", "Assign specialist questions to qualified professionals."],
    relatedProductSlug: "deal-room-toolkit",
  },
  {
    slug: "understanding-property-charges",
    index: "05",
    title: "Beyond Base Price: Understanding Property Charges",
    category: "Investment basics",
    summary: "A buyer-friendly introduction to charges and commitments that may sit outside a headline property price.",
    deck: "A starting price helps discovery, but a purchase decision needs a dated and property-specific view of the complete commitment.",
    readTime: "7 min read",
    hero: { src: "/media/blueprint-hands.jpg", alt: "Hands reviewing plans and project documents", width: 2048, height: 3072 },
    thesis: "Ask for a complete cost sheet, understand which figures are fixed or estimated, and verify taxes, registration, finance, and other obligations for your circumstances.",
    sections: [
      { heading: "Read the dated cost sheet", paragraphs: ["The cost sheet should identify the unit, area basis, base consideration, premiums, parking, deposits, maintenance-related amounts, taxes, registration, and other applicable items.", "Terminology and applicability vary. Ask for plain-language explanations and current supporting information."], fieldNote: "Mark every line as included, additional, estimated, refundable, recurring, or still to be confirmed." },
      { heading: "Bring timing into the calculation", paragraphs: ["Payment plans, construction stage, finance structure, possession timing, fit-out, interim housing, and recurring charges affect cash flow as well as total cost.", "A lower headline number may not be the lower commitment once timing and exclusions are considered." ] },
      { heading: "Use the right professional input", paragraphs: ["Tax, finance, legal, valuation, engineering, and property-specific advice should come from appropriately qualified professionals using current documents.", "Educational material can help you ask the questions; it cannot calculate or approve the transaction for you." ] },
    ],
    carryForward: ["Request a dated, unit-specific cost sheet.", "Separate fixed, estimated, recurring, and excluded items.", "Verify tax, finance, legal, and property-specific obligations independently."],
    relatedProductSlug: "basics-of-real-estate-training-deck",
  },
] as const;
